### ISSUE TITLE
Turn off engine problems

### ISSUE THREAD

**Issue by sirmarknlddr** [ArkSeyonet/esx_aiomenu#1]
The engine automatically turns back on after turning it off with the AIOMENU. I have no scripts installed like "keep engine on". This is occuring since the latest FiveM client update.

**Comment by ArkSeyonet** [comment]
I am going to look into if this issue is occuring in the latest update soon, and if so I will try to provide something that fixes. Sorry, I've been on a hiatus while going to school.

**Comment by ArkSeyonet** [comment]
Fixed this issue in latest version.
