### ISSUE TITLE
Can't close the menu via Esc

### ISSUE THREAD

**Issue by MoravianLion** [ArkSeyonet/esx_aiomenu#2]
NUI focus is still on when I am pressing Esc. Clean install.

**Comment by ArkSeyonet** [comment]
I will look into this, it is probably very outdated and I will try to update the script to work with all of the new updates. I've been on a hiatus thanks to school, but I should begin working on it again soon.

**Comment by ArkSeyonet** [comment]
I could not reproduce this, but it won't be an issue once the UI is converted in the future.
