### ISSUE TITLE
Punching

### ISSUE THREAD

**Issue by Schwardo19462** [ArkSeyonet/esx_aiomenu#6]
Is it possible to coding somethin inside these script's if i using this Menu or all other ESX menu to stop Punching? Because every Time i click on my Mouse to select somethin the Model punching every Person in my near :(

**Comment by ArkSeyonet** [comment]
The issue isn't happening to a lot of people, so if you join the discord and message me there, I will help you fix the problem for your own server, because the change in the script that would fix it would create more problems, since it doesn't happen to many people.
