### ISSUE TITLE
Issue changing default Page Up key

### ISSUE THREAD

**Issue by iLlama** [ArkSeyonet/esx_aiomenu#7]
I have scoured all config files included and cannot find where Page Up as the default key is called. I would like to change it and know enough to do so, but I have been through all files and don't see where that key is called. Is it hard-coded somehow?

**Comment by Demo4889** [comment]
> 
> 
> I have scoured all config files included and cannot find where Page Up as the default key is called. I would like to change it and know enough to do so, but I have been through all files and don't see where that key is called. Is it hard-coded somehow?

This is found in the client/main.lua file under line 24 (if unchanged)

`if IsControlJustPressed(1, 10) and GetLastInputMethod( 0 ) then`

Change the 10 to whatever key you want using the keys provided in [FiveM Controls](https://docs.fivem.net/game-references/controls/)
